<?php
$z[0]=Array("arcurl","",47,62);
$z[1]=Array("global","if(@me%2==0)@me=\" class=\\\"mar20\\\">\";else @me=\">\";",79,185);
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("pubdate","",445,491);
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("pubdate","",565,614);
$z[3][4]['function']="strftime(\"%Y-%m\",@me)";
$z[4]=Array("fulltitle","",954,972);
$z[5]=Array("description","",1221,1241);

?>