<?php
$z[0]=Array("path","\r\n            \$p = explode(',', @me); array_pop(\$p); \$len = count(\$p); if(\$len>=1){ @me = '\r\n            <li>\r\n                <img src=\"/zkadmin/'.\$p[0].'\">\r\n            </li>\r\n            <li>\r\n                <img src=\"/zkadmin/'.\$p[1].'\">\r\n            </li>\r\n            <li>\r\n                <img src=\"/zkadmin/'.\$p[2].'\">\r\n            </li>\r\n            '; } ",0,403);
$z[0][4]['runphp']="yes";

?>