<li class="">
                                <div class="bg-pic2"><img src="/images/news_01_a.jpg" alt=""></div>
                                <div class="bg-pic">
                                    <img src="/images/news_01.jpg" alt="">
                                </div>
                                <div class="des">
                                    <div class="table">
                                        <div class="table-cell">
                                            <div class="num">1</div>
                                            <div class="day">23</div>
                                            <div class="date">201-03</div>
                                        </div>
                                    </div>
                                </div>
                            </li>