<field:content itemname="公告内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:content>
<field:yc_xmlb itemname="收益类别" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yc_xmlb>

<field:yc_cplx itemname="产品类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yc_cplx>

<field:yc_cpmc itemname="产品名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yc_cpmc>
