<div class="des" style="text-align: left;border: 1px solid #6D3D1F;
                width: 938px;height:auto;
                line-height: 30px;
                overflow: hidden;
                margin:0 auto ">
                    <div class="right" id="div_all[field:id/]">
                    	<div class="title" style="font-size: 2.5em;
            margin: 25px 35px;color:#C49715">
                            [field:fulltitle/]<!-- 招聘标题-->
                    	</div>
                        <div style="margin-left: 45px">
                            [field:shorttitle/]
                        </div>
                        <div id="[field:id/]" style="display: none">
                            [field:body/]
                        </div>
                        <span id="span_[field:id/]" style="margin-left: 95%;">>></span>
                    </div>
		        </div>
			      <div class="mainblank40"></div>