<li class="">
                                <div class="bg-pic2"><img src="[field:small/]" alt="[field:fulltitle/]"></div>
                                <div class="bg-pic">
                                    <img src="[field:litpic/]" alt="[field:fulltitle/]">
                                </div>
                                <div class="des">
                                    <div class="table">
                                        <div class="table-cell">
                                            <div class="num">[field:global.autoindex/]</div>
                                            <div class="day">[field:pubdate function='strftime("%d",@me)'/]</div>
                                            <div class="date">[field:pubdate function='strftime("%Y-%m",@me)'/]</div>
                                        </div>
                                    </div>
                                </div>
                            </li>