<div class="des" style="text-align: left;border: 1px solid #6D3D1F;
                width: 938px;height:auto;
                overflow: hidden;
                margin:0 auto ">
                    <div class="right">
                    	<div class="title">
				[field:fulltitle/]   <!-- 招聘标题-->
                    	</div>
                        [field:body/]<!-- 招聘内容-->
                    </div>
		</div>
			      <div class="mainblank20"></div>