	
<field:onlynet itemname="联系方式限制" autofield="1" type="int" isnull="true" default="1"  maxlength="250" issearch="" isshow="" state="1">	
</field:onlynet>	
	
<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女,保密"  maxlength="250" issearch="" isshow="" state="1">	
</field:sex>	
	
<field:uname itemname="昵称/公司名称" autofield="1" type="textchar" isnull="true" default=""  maxlength="30" issearch="" isshow="" state="1">	
</field:uname>	
	
<field:qq itemname="QQ" autofield="1" type="textchar" isnull="true" default=""  maxlength="12" issearch="" isshow="" state="1">	
</field:qq>	
	
	
	
<field:tel itemname="电话号码" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="1">	
</field:tel>	
	
<field:mobile itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="1">	
</field:mobile>	
	
<field:place itemname="目前所在地" autofield="1" type="int" default="0"  maxlength="5" issearch="0" isshow="0" state="1">	
</field:place>	
	
	
	
	
	
	
	
	
	
<field:income itemname="收入" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:income>	
	
<field:education itemname="学历" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:education>	
	
<field:height itemname="身高" autofield="1" type="int" isnull="true" default="160"  maxlength="5" issearch="" isshow="" state="1">	
</field:height>	
	
	
	
<field:blood itemname="血型" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:blood>	
	
<field:vocation itemname="职业" autofield="1" type="text" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:vocation>	
	
<field:smoke itemname="吸烟" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:smoke>	
	
<field:marital itemname="婚姻状况" autofield="1" type="text" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:marital>	
	
<field:house itemname="住房" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:house>	
	
	
	
	
	
	
	
	
	
	
	
	
<field:address itemname="家庭住址" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:address>	
	
<field:uptime itemname="更新时间" autofield="1" type="int" isnull="true" default=""  maxlength="10" issearch="" isshow="" state="1">	
</field:uptime>	
