<?php
$z[0]=Array("arcurl","",47,62);
$z[1]=Array("array","  \r\nif(@me['flag']=='c'){  \r\n@me=\" class=\\\"theme-login\\\">\";  \r\n}  \r\nelse {  \r\n@me=\" class=\\\"list-a\\\">\";  \r\n}  \r\n",64,216);
$z[1][4]['runphp']="yes";
$z[2]=Array("pubdate","",477,523);
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("pubdate","",597,646);
$z[3][4]['function']="strftime(\"%Y-%m\",@me)";
$z[4]=Array("fulltitle","",986,1004);
$z[5]=Array("description","",1253,1273);

?>