<div class="des" style="text-align: left;border: 1px solid #6D3D1F;
                width: 938px;height:auto;
                line-height: 30px;
                overflow: hidden;
                margin:0 auto ">
                    <div class="right">
                    	<div class="title">
				[field:fulltitle/]   <!-- 招聘标题-->
                    	</div>
                        <div id="div_text">
                            function="cn_substr(@me,250)"/
                        </div>
                    </div>
		</div>
			      <div class="mainblank20"></div>