<a href="view.php?aid=[field:id/]" >
                <div class="des">
                    <div class="left"><img src="[field:small/]" alt="[field:fulltitle/]" border="0" align="middle" alt="[field:title/]" width="300" height="168">
                    </div>
                    <div class="right">
                    	<div class="title"><!-- 
				<span>[field:pubdate function='strftime("%d",@me)'/]</span> / [field:pubdate function='strftime("%m",@me)'/]   -->
				[field:fulltitle/]
                    	</div>
				[field:description/]
                    	<div class="qaq">查看详情>></div>
                    </div>
		</div>
			      <div class="mainblank20"> </div>


                             </a>