<a href="[field:arcurl/]"  target= _blank>
                <div class="des">
                    <div class="left"><img src="[field:small/]" alt="[field:fulltitle/]" border="0" align="middle" alt="[field:title/]" width="300" height="168">
                    </div>
                    <div class="right">
                    	<div class="title">
				[field:fulltitle/]
                    	</div>
				[field:description/]
                    	<div class="sqqaq">[field:pubdate function="MyDate('Y-m-d',@me)"/]<span>查看详情>></span></div>
                    </div>
		</div>
			      <div class="mainblank20">&nbsp;</div>


                             </a>