<?php
$z[0]=Array("small","",69,83);
$z[1]=Array("fulltitle","",90,108);
$z[2]=Array("arcurl","",217,232);
$z[3]=Array("litpic","",244,259);
$z[4]=Array("fulltitle","",266,284);
$z[5]=Array("global","",567,592);
$z[5][4]['name']="autoindex";
$z[6]=Array("pubdate","",661,707);
$z[6][4]['function']="strftime(\"%d\",@me)";
$z[7]=Array("pubdate","",777,826);
$z[7][4]['function']="strftime(\"%Y-%m\",@me)";

?>