<div class="content-center">
			    <div class="containerT">
			      <h2><strong>投资业务</strong></h2>
			      <h4><strong><B>INVESTMENT PORTFOLIO</B></strong></h4>
			    </div>
		    </div>
                    <div class="en">
                        <div class="line line1"><span class="cirle"></span></div>{dede:field.english/}<div class="line line2"><span class="cirle"></span></div>
                    </div>