<?php
$z[0]=Array("small","",69,83);
$z[1]=Array("fulltitle","",90,108);
$z[2]=Array("arcurl","",217,232);
$z[3]=Array("array","  \r\nif(@me['flag']=='c,p,j'){  \r\n@me=\" class=\\\"theme-login\\\">\";  \r\n}  \r\nelse {  \r\n@me=\" class=\\\"list-a\\\">\";  \r\n}  \r\n",234,390);
$z[3][4]['runphp']="yes";
$z[4]=Array("litpic","",402,417);
$z[5]=Array("fulltitle","",424,442);
$z[6]=Array("global","",725,750);
$z[6][4]['name']="autoindex";
$z[7]=Array("pubdate","",819,865);
$z[7][4]['function']="strftime(\"%d\",@me)";
$z[8]=Array("pubdate","",935,984);
$z[8][4]['function']="strftime(\"%Y-%m\",@me)";

?>