<a href="view.php?aid=[field:id/]" >
                <div class="des">
                    <div class="left"><img src="[field:small/]" alt="[field:fulltitle/]" border="0" align="middle" alt="[field:title/]" width="300" height="168">
                    </div>
                    <div class="right">
                    	<div class="title">
				[field:fulltitle/]
                    	</div>
                        [field:body  function="cn_substr(@me,500)"/]
                    </div>
		</div>
			      <div class="mainblank20">&nbsp;</div>


                             </a>