<li class="typeid{dede:field.id/}">
                        <a href="{dede:field.typeurl/}">{dede:field.typename/}</a>
                        <ul class="sub-nav">
                            
                            {dede:channel type='son' noself='yes'}
                            <li><a href="[field:typelink/]">[field:typename/]</a></li>
                            {/dede:channel}
                            
                        </ul>
                    </li>