<a href="casedetail-24-472.html">
                	<div class="img"><img src="upload/201708/16/201708161450299951.jpg" alt="悉尼Campsie公寓开发项目"></div>
                    <div class="text">
                    <div class="h3"><strong>悉尼Campsie公寓开发项目</strong><em></em></div>
                    <div class="em">——</div>
                    <div class="p">位于悉尼内城区城市副中心——Campsie板块的最核心位置…</div>
                    </div>
                    </a>