<?php
$z[0]=Array("arcurl","",11,26);
$z[1]=Array("small","",93,107);
$z[2]=Array("fulltitle","",114,132);
$z[3]=Array("litpic","",242,257);
$z[4]=Array("fulltitle","",264,282);
$z[5]=Array("global","",561,586);
$z[5][4]['name']="autoindex";
$z[6]=Array("pubdate","",655,701);
$z[6][4]['function']="strftime(\"%d\",@me)";
$z[7]=Array("pubdate","",771,820);
$z[7][4]['function']="strftime(\"%Y-%m\",@me)";

?>