<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",18,95);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",122,138);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",140,225);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",256,271);
$z[4]=Array("imgwidth","",285,303);
$z[5]=Array("alttext","",309,326);
$z[6]=Array("ddimg","",371,385);
$z[7]=Array("linkurl","",445,461);
$z[8]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",463,549);
$z[8][4]['runphp']="yes";
$z[9]=Array("title","",569,584);
$z[10]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",624,704);
$z[10][4]['runphp']="yes";

?>