<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,187);
$z[2][4]['filename']="meta.htm";
$z[3]=Array("include","",340,375);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",599,621);
$z[4][4]['name']="position";
$z[5]=Array("field","",718,739);
$z[5][4]['name']="content";
$z[6]=Array("include","",828,865);
$z[6][4]['filename']="footer.htm";

?>