<?php
$z[0]=Array("arcurl","",47,62);
$z[1]=Array("array","if(@me['flag']=='c')@me=\" class=\\\"theme-login\\\">\";else @me=\" class=\\\"list-a\\\">\";",65,185);
$z[1][4]['runphp']="yes";
$z[2]=Array("pubdate","",444,490);
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("pubdate","",564,613);
$z[3][4]['function']="strftime(\"%Y-%m\",@me)";
$z[4]=Array("fulltitle","",953,971);
$z[5]=Array("description","",1220,1240);

?>