<div id="div_all" class="des" style="text-align: left;border: 1px solid #6D3D1F;
                width: 938px;height:auto;
                line-height: 30px;
                overflow: hidden;
                margin:0 auto ">
                    <div class="right">
                    	<div class="title">
                            [field:fulltitle/]<!-- 招聘标题-->
                    	</div>
                        <div id="[field:id/]" style="display: none">
                            [field:body/]
                        </div>
                        <span id="span[field:id/]" onclick="func_click()">查看详情>> </span>
                    </div>
		        </div>
			      <div class="mainblank20"></div>