<li>
                        <div class="title">[field:fulltitle/] <br>[field:description/]</div><br><br>
                        <div class="des">
                            [field:body/]
                            <p style="font-size: 16px;">岗位职责：</p>
                            1、负责ZAKER的接口开发；<br>
                            2、负责ZAKER的采集技术开发；<br>
                            3、负责ZAKER的管理后台开发。<br><br><br>
                            <p style="font-size: 16px;">任职要求：</p>
                            1、两年以上PHP工作经验、对PHP语言有深入的了解；熟悉PHP开发语言及面向对象的软件设计方法；<br>
                            2、熟练掌握MySQL数据库，了解MongoDB或node.js技术的优先考虑；<br>
                            3、熟练掌握XHTML、CSS、DIV、Javascript、ajax等页面技术；<br>
                            4、具备良好的代码编程习惯及文档编写能力；<br>
                            5、有优秀的学习新知识的能力，思维灵活；<br>
                            6、熟悉开源PHP框架一种以上，并有一年以上实际项目应用经验；<br>
                            7、善于与人沟通，良好的团队合作精神和高度的责任感，能够承受压力，有较强的吃苦耐劳和创新精神。
                        </div>
                    </li>