<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,187);
$z[2][4]['filename']="meta.htm";
$z[3]=Array("include","",340,375);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",509,529);
$z[4][4]['name']="arcpic";
$z[5]=Array("field","",536,558);
$z[5][4]['name']="typename";
$z[6]=Array("include","",1750,1787);
$z[6][4]['filename']="footer.htm";

?>