<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,189);
$z[2][4]['filename']="meta_m.htm";
$z[3]=Array("include","",342,379);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("field","",1103,1125);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n        <div class=\"des\" style=\"text-align: left;border: 1px solid #6D3D1F;\r\n                width: 938px;height:auto;\r\n                line-height: 30px;\r\n                overflow: hidden;\r\n                margin:0 auto \">\r\n            <div class=\"right\" id=\"div_all[field:id/]\">\r\n                <div class=\"title\" style=\"font-size: 2.5em;\r\n            margin: 25px 35px;color:#C49715\">\r\n                    [field:fulltitle/]<!-- 招聘标题-->\r\n                </div>\r\n                <div style=\"margin-left: 45px\">\r\n                    [field:shorttitle/]\r\n                </div>\r\n                <div id=\"[field:id/]\" style=\"display: none\">\r\n                    [field:body/]\r\n                </div>\r\n                <span id=\"span_[field:id/]\" style=\"margin-left: 95%;\">>></span>\r\n            </div>\r\n        </div>\r\n        <div class=\"mainblank20\"></div>\r\n\r\n        ",1269,2214);
$z[5][4]['orderby']="sortrank";
$z[5][4]['flag']="c,p";
$z[5][4]['pagesize']="6";
$z[6]=Array("include","",2335,2374);
$z[6][4]['filename']="footer_m.htm";

?>