<?php
$z[0]=Array("arcurl","",9,24);
$z[1]=Array("small","",127,141);
$z[2]=Array("fulltitle","",148,166);
$z[3]=Array("title","",199,213);
$z[4]=Array("pubdate","",369,415);
$z[4][4]['function']="strftime(\"%d\",@me)";
$z[5]=Array("pubdate","",425,471);
$z[5][4]['function']="strftime(\"%m\",@me)";
$z[6]=Array("fulltitle","",493,511);
$z[7]=Array("description","",546,566);
$z[8]=Array("pubdate","",608,655);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>