<li>
		                                <div class="imag2"><a href="[field:arcurl/]" title="[field:title/]" target= _blank>
		                                    <div class="imag2a">
		                                        <img src="[field:small/]"></div></a></div>
		                                <div class="textc2">
		                                    <h1><a href="[field:arcurl/]" title="[field:title/]" target= _blank>[field:fulltitle/]</a></h1>
		                                    <a href="[field:arcurl/]" title="[field:title/]" target= _blank><span class="texccc">
		                                          [field:description/]</span>
		                                    <span class="paaf">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></a>
		                                </div>
		                            </li>