
<field:ziduan1 itemname="字段1" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ziduan1>

<field:ziduan2 itemname="字段2" autofield="1" type="select" isnull="true" default="字段,字段"  maxlength="250" page="">
</field:ziduan2>

<field:ziduan3 itemname="字段3" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:ziduan3>

<field:ziduan4 itemname="字段4" autofield="1" type="img" isnull="true" default=""  maxlength="250" page="">
</field:ziduan4>
