<li>
                        <a href="{dede:field.typeurl/}">
                            <div class="pic">
                                <img src="{dede:field.arcpic/}" alt="{dede:field.typename/}">
                            </div>
                            <div class="title">{dede:field.typename/}</div>
                            <div class="star"></div>
                            <div class="des">
                                <div class="table">
                                    <div class="table-cell">
                                        {dede:field.description/}
                                    </div>
                                </div>
                            </div>
                            <div class="line"></div>
                        </a>
                    </li>