<?php
$z[0]=Array("arcurl","",47,62);
$z[1]=Array("global","if(@me['flag']=='c')@me=\" class=\\\"theme-login\\\">\";else @me=\" class=\\\"list-a\\\">\";",65,202);
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("pubdate","",461,507);
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("pubdate","",581,630);
$z[3][4]['function']="strftime(\"%Y-%m\",@me)";
$z[4]=Array("fulltitle","",970,988);
$z[5]=Array("description","",1237,1257);

?>