<?php
$z[0]=Array("channelartlist","\r\n                    <li class=\"typeid{dede:field.id/}\">\r\n                        <a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n                    </li>\r\n                    ",525,771);
$z[0][4]['typeid']="1,1";
$z[1]=Array("channelartlist","\r\n                    <li class=\"typeid{dede:field.id/}\">\r\n                        <a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n                        <ul class=\"sub-nav\">\r\n                            \r\n                            {dede:channel type='son' noself='yes'}\r\n                            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                            {/dede:channel}\r\n                            \r\n                        </ul>\r\n                    </li>\r\n                    ",793,1377);
$z[1][4]['typeid']="2,2";
$z[2]=Array("channelartlist","\r\n                    <li class=\"typeid{dede:field.id/}\">\r\n                        <a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n                    </li>\r\n                    ",1399,1647);
$z[2][4]['typeid']="3,4,5";

?>