<?php
$z[0]=Array("global","",389,415);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channelartlist","\r\n		                    <li class=\"typeid{dede:field.id/}\">\r\n		                        <a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n		                        <ul class=\"sub-nav\">\r\n		                            {dede:channel type='son' noself='yes'}\r\n		                            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n		                            {/dede:channel}\r\n		                        </ul>\r\n		                    </li>\r\n		                    ",748,1302);
$z[1][4]['typeid']="2,1,2,18,3,30,5";

?>