<?php
$z[0]=Array("global","",112,138);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",214,239);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n            <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n            ",271,519);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";

?>