<?php
$z[0]=Array("global","",87,113);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",158,181);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",225,251);
$z[2][4]['name']="description";
$z[3]=Array("include","",261,296);
$z[3][4]['filename']="meta.htm";
$z[4]=Array("include","",452,487);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channelartlist","\r\n                    <div class=\"cn\">{dede:field.typename/}</div>\r\n                    <div class=\"en\">\r\n                        <div class=\"line line1\"><span class=\"cirle\"></span></div>{dede:field.english/}<div class=\"line line2\"><span class=\"cirle\"></span></div>\r\n                    </div>\r\n                    ",1763,2134);
$z[5][4]['typeid']="2,2";
$z[6]=Array("channelartlist","\r\n                    <li>\r\n                        <a href=\"{dede:field.typeurl/}\">\r\n                            <div class=\"pic\">\r\n                                <img src=\"{dede:field.arcpic/}\" alt=\"{dede:field.typename/}\">\r\n                            </div>\r\n                            <div class=\"title\">{dede:field.typename/}</div>\r\n                            <div class=\"star\"></div>\r\n                            <div class=\"des\">\r\n                                <div class=\"table\">\r\n                                    <div class=\"table-cell\">\r\n                                        {dede:field.description/}\r\n                                    </div>\r\n                                </div>\r\n                            </div>\r\n                            <div class=\"line\"></div>\r\n                        </a>\r\n                    </li>\r\n                    ",2230,3167);
$z[6][4]['typeid']="2";
$z[6][4]['row']="4";
$z[7]=Array("channelartlist","\r\n                    <div class=\"cn\">{dede:field.typename/}</div>\r\n                    <div class=\"en\">\r\n                        <div class=\"line line1\"><span class=\"cirle\"></span></div>{dede:field.english/}<div class=\"line line2\"><span class=\"cirle\"></span></div>\r\n                    </div>\r\n                    ",3357,3730);
$z[7][4]['typeid']="16,16";
$z[8]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:body/]\" target=\"_blank\">\r\n                            <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\">\r\n                        </a>\r\n                    </li>\r\n                    ",3821,4171);
$z[8][4]['typeid']="16";
$z[8][4]['row']="5000";
$z[8][4]['orderby']="hot";
$z[8][4]['addfields']="body";
$z[8][4]['channelid']="1";
$z[9]=Array("include","",4292,4329);
$z[9][4]['filename']="footer.htm";

?>