<?php
$z[0]=Array("global","",87,113);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",158,181);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",225,251);
$z[2][4]['name']="description";
$z[3]=Array("include","",261,296);
$z[3][4]['filename']="meta.htm";
$z[4]=Array("include","",452,487);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:body/]\" target=\"_blank\">\r\n                            <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\">\r\n                        </a>\r\n                    </li>\r\n                    ",12665,13015);
$z[5][4]['typeid']="16";
$z[5][4]['row']="5000";
$z[5][4]['orderby']="hot";
$z[5][4]['addfields']="body";
$z[5][4]['channelid']="1";
$z[6]=Array("include","",13136,13173);
$z[6][4]['filename']="footer.htm";

?>