<?php
$z[0]=Array("global","",87,113);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",158,181);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",225,251);
$z[2][4]['name']="description";
$z[3]=Array("include","",261,296);
$z[3][4]['filename']="meta.htm";
$z[4]=Array("include","",452,487);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n		                            <li>\r\n		                                <div class=\"imag2\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target= _blank>\r\n		                                    <div class=\"imag2a\">\r\n		                                        <img src=\"[field:small/]\"></div></a></div>\r\n		                                <div class=\"textc2\">\r\n		                                    <h1><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target= _blank>[field:fulltitle/]</a></h1>\r\n		                                    <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target= _blank><span class=\"texccc\">\r\n		                                          [field:description/]</span>\r\n		                                    <span class=\"paaf\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a>\r\n		                                </div>\r\n		                            </li>\r\n          ",4615,5615);
$z[5][4]['addfields']="small";
$z[5][4]['channelid']="1";
$z[5][4]['typeid']="26";
$z[5][4]['row']="3";
$z[5][4]['titlelen']="32";
$z[5][4]['noflag']="h";
$z[6]=Array("arclist","\r\n						<li>\r\n							<div class=\"imag2\">\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=_ blank>\r\n									<div class=\"imag2a\">\r\n										<img src=\"[field:small/]\">\r\n									</div>\r\n								</a>\r\n							</div>\r\n							<div class=\"textc2\">\r\n								<h1>\r\n									<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=_ blank>[field:fulltitle/]</a>\r\n								</h1>\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=_ blank>\r\n									<span class=\"texccc\">\r\n										[field:description/]</span>\r\n									<span class=\"paaf\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n								</a>\r\n							</div>\r\n						</li>\r\n						",6528,7293);
$z[6][4]['addfields']="small";
$z[6][4]['channelid']="1";
$z[6][4]['typeid']="26";
$z[6][4]['row']="3";
$z[6][4]['titlelen']="32";
$z[6][4]['noflag']="h";
$z[7]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:body/]\" target=\"_blank\">\r\n                            <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\">\r\n                        </a>\r\n                    </li>\r\n                    ",7953,8303);
$z[7][4]['typeid']="16";
$z[7][4]['row']="5000";
$z[7][4]['orderby']="hot";
$z[7][4]['addfields']="body";
$z[7][4]['channelid']="1";
$z[8]=Array("include","",8424,8461);
$z[8][4]['filename']="footer.htm";

?>