<?php
$z[0]=Array("global","",87,113);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",158,181);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",225,251);
$z[2][4]['name']="description";
$z[3]=Array("include","",261,298);
$z[3][4]['filename']="meta_m.htm";
$z[4]=Array("include","",454,491);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("arclist","\r\n                	<a href=\"/m[field:arcurl/]\">\r\n                	<div><img src=\"[field:small/]\" alt=\"[field:title/]\" class=\"imgm\"></div>\r\n                    </a>\r\n          ",1923,2200);
$z[5][4]['addfields']="small";
$z[5][4]['channelid']="1";
$z[5][4]['typeid']="32";
$z[5][4]['row']="1";
$z[5][4]['titlelen']="32";
$z[5][4]['noflag']="h";
$z[6]=Array("arclist","\r\n                	<a href=\"view.php?aid=[field:id/]\">\r\n                	<div class=\"img\"><img src=\"[field:small/]\" alt=\"[field:title/]\"></div>\r\n                    <div class=\"text\">\r\n                    <div class=\"h3\"><strong>[field:title/]</strong><em></em></div>\r\n                    <div class=\"p\">[field:description/]...</div>\r\n                    </div>\r\n                    </a>\r\n          ",2594,3095);
$z[6][4]['addfields']="small";
$z[6][4]['channelid']="1";
$z[6][4]['typeid']="26";
$z[6][4]['row']="1";
$z[6][4]['titlelen']="32";
$z[6][4]['noflag']="h";
$z[7]=Array("arclist","\r\n                	<a href=\"view.php?aid=[field:id/]\">\r\n                	<div><img src=\"[field:small/]\" alt=\"[field:title/]\" class=\"imgm\"></div>\r\n                    </a>\r\n          ",3440,3724);
$z[7][4]['addfields']="small";
$z[7][4]['channelid']="1";
$z[7][4]['typeid']="29";
$z[7][4]['row']="1";
$z[7][4]['titlelen']="32";
$z[7][4]['noflag']="h";
$z[8]=Array("include","",3916,3955);
$z[8][4]['filename']="footer_m.htm";

?>