<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,189);
$z[2][4]['filename']="meta_m.htm";
$z[3]=Array("include","",343,380);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("field","",1230,1252);
$z[4][4]['name']="position";
$z[5]=Array("field","",1377,1398);
$z[5][4]['name']="content";
$z[6]=Array("include","",1480,1519);
$z[6][4]['filename']="footer_m.htm";

?>