<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,189);
$z[2][4]['filename']="meta_m.htm";
$z[3]=Array("include","",1304,1341);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("field","",2092,2114);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n                             <a href=\"view.php?aid=[field:id/]\" >\r\n                <div class=\"des\">\r\n                    <div class=\"left\"><img src=\"[field:small/]\" alt=\"[field:fulltitle/]\" border=\"0\" align=\"middle\" alt=\"[field:title/]\" width=\"300\" height=\"168\">\r\n                    </div>\r\n                    <div class=\"right\">\r\n                    	<div class=\"title\">\r\n				[field:fulltitle/]\r\n                    	</div>\r\n				[field:description/]\r\n                    	<div class=\"sqqaq\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]<span>查看详情>></span></div>\r\n                    </div>\r\n		</div>\r\n			      <div class=\"mainblank20\">&nbsp;</div>\r\n\r\n\r\n                             </a>  \r\n\r\n\r\n\r\n\r\n                            ",2459,3267);
$z[5][4]['orderby']="sortrank";
$z[5][4]['flag']="c,p";
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",3414,3480);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",4536,4575);
$z[7][4]['filename']="footer_m.htm";

?>