<?php
$z[0]=Array("field","",87,106);
$z[0][4]['name']="title";
$z[1]=Array("global","",109,135);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",149,184);
$z[2][4]['filename']="meta.htm";
$z[3]=Array("include","",337,372);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",506,526);
$z[4][4]['name']="arcpic";
$z[5]=Array("field","",533,555);
$z[5][4]['name']="typename";
$z[6]=Array("channelartlist","\r\n                    <div class=\"cn\">{dede:field.typename/}</div>\r\n                    <div class=\"en\">\r\n                        <div class=\"line line1\"><span class=\"cirle\"></span></div>{dede:field.english/}<div class=\"line line2\"><span class=\"cirle\"></span></div>\r\n                    </div>\r\n                    ",734,1105);
$z[6][4]['typeid']="3,3";
$z[7]=Array("field","",1215,1234);
$z[7][4]['name']="title";
$z[8]=Array("field","",1287,1344);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[9]=Array("field","",1420,1441);
$z[9][4]['name']="content";
$z[10]=Array("include","",1624,1661);
$z[10][4]['filename']="footer.htm";

?>