<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,189);
$z[2][4]['filename']="meta_m.htm";
$z[3]=Array("include","",1305,1342);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("field","",2002,2024);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n                             <a href=\"view.php?aid=[field:id/]\" >\r\n                <div class=\"des\">\r\n                    <div class=\"left\"><img src=\"[field:small/]\" alt=\"[field:fulltitle/]\" border=\"0\" align=\"middle\" alt=\"[field:title/]\" width=\"300\" height=\"168\">\r\n                    </div>\r\n                    <div class=\"right\">\r\n                    	<div class=\"title\"><!-- \r\n				<span>[field:pubdate function='strftime(\"%d\",@me)'/]</span> / [field:pubdate function='strftime(\"%m\",@me)'/]   -->\r\n				[field:fulltitle/]\r\n                    	</div>\r\n				[field:description/]\r\n                    	<div class=\"qaq\">查看详情>></div>\r\n                    </div>\r\n		</div>\r\n			      <div class=\"mainblank20\"> </div>\r\n\r\n\r\n                             </a>  \r\n\r\n\r\n\r\n\r\n                            ",2335,3204);
$z[5][4]['orderby']="sortrank";
$z[5][4]['flag']="c,p";
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",3351,3417);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",4457,4496);
$z[7][4]['filename']="footer_m.htm";

?>