<?php
$z[0]=Array("field","",87,109);
$z[0][4]['name']="typename";
$z[1]=Array("global","",112,138);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",152,187);
$z[2][4]['filename']="meta.htm";
$z[3]=Array("include","",340,375);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",505,525);
$z[4][4]['name']="arcpic";
$z[5]=Array("field","",532,554);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n                        <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n                        ",911,1148);
$z[6][4]['type']="self";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("list","\r\n                    <li>\r\n                        <div class=\"title\"><b>[field:fulltitle/]</b><br>[field:description/]</div><br><br>\r\n                        <div class=\"des\">\r\n                            [field:body/]\r\n                        </div>\r\n                    </li>\r\n                    ",1304,1690);
$z[7][4]['orderby']="hot";
$z[7][4]['pagesize']="10000";
$z[7][4]['addfields']="body";
$z[7][4]['channelid']="1";
$z[8]=Array("include","",2252,2289);
$z[8][4]['filename']="footer.htm";

?>